version: '3.8'
name: vaultwarden

services:
  vaultwarden.server:
    container_name: vaultwarden-server
    image: vaultwarden/server:1.30.5
    depends_on:
      vaultwarden.db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@vaultwarden-db:5432/${DATABASE_NAME}
      - ROCKET_TLS={certs="/ssl/fullchain.pem",key="/ssl/privkey.pem"}
      - ADMIN_TOKEN=${SERVER_ADMIN_TOKEN}
    volumes:
      - ${SERVER_DATA_PATH}:/data
      - ${SERVER_SSL_PATH}:/ssl
    ports:
      - ${SERVER_PORT}:80

  vaultwarden.db:
    container_name: vaultwarden-db
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${DATABASE_DATA_PATH}:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
